# Generated by Django 3.0.2 on 2020-02-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitie',
            name='is_done',
            field=models.BooleanField(blank=True),
        ),
    ]
