# Generated by Django 3.0.2 on 2020-03-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20200227_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitie',
            name='is_done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
