# Generated by Django 3.0.2 on 2020-03-03 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0003_auto_20200303_1550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activitie',
            new_name='Activity',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activitie',
            new_name='activity',
        ),
    ]
